### ISSUE TITLE
AttributeError: module 'psutil' has no attribute 'sensors_temperatures'

### ISSUE THREAD

**Issue by fryfrog** [pimoroni/fanshim-python#10]
This raspbian install was done following the guide at https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-fan-shim, basically just `sudo ./install.sh` and `sudo ./examples/install-service.sh 65 5`.

https://github.com/giampaolo/psutil/issues/1271

Maybe an old version of python-psutil?

```
0 ✓ fryfrog@raspbian-armv7l ~ $ sudo /home/fryfrog/fanshim-python/examples/automatic.py --threshold 55 --hysteresis 5 --delay 2
Traceback (most recent call last):
  File "/home/fryfrog/fanshim-python/examples/automatic.py", line 70, in <module>
    t = get_cpu_temp()
  File "/home/fryfrog/fanshim-python/examples/automatic.py", line 38, in get_cpu_temp
    return psutil.sensors_temperatures()['cpu-thermal'][0].current
AttributeError: module 'psutil' has no attribute 'sensors_temperatures'
```

**Comment by fryfrog** [comment]
I used `pip` and `pip3` to install the latest version, but the error persists.

```
0 ✓ fryfrog@raspbian-armv7l ~ $ python3 -c "import psutil; print(psutil.__version__)"
5.6.3
0 ✓ fryfrog@raspbian-armv7l ~ $ python -c "import psutil; print(psutil.__version__)"
5.6.3
```

**Comment by fryfrog** [comment]
And after *removing* the `apt` versions of `psutil` and `rpi.gpio`, it doesn't even see they're there, even though the above test works fine. I don't know enough debian python yet to understand why. :/

```
0 ✓ fryfrog@raspbian-armv7l ~ $ sudo ./automatic.py
Traceback (most recent call last):
  File "./automatic.py", line 3, in <module>
    import psutil
ImportError: No module named 'psutil'
```

**Comment by fryfrog** [comment]
Ugh, this was so easy... running `pip` as yourself installs it for yourself, the script runs as `root` so needs to be installed by root.
