### ISSUE TITLE
What is cpu-thermal?

### ISSUE THREAD

**Issue by fryfrog** [pimoroni/fanshim-python#9]
I can't figure out what `cpu-thermal` is, can someone explain it? I assumed it was a raspbian binary/command, but when I did an install on one, it didn't install anything that provided that command.

https://github.com/pimoroni/fanshim-python/blob/master/examples/automatic.py#L38

```
0 ✓ fryfrog@arch-aarch64 ~ $ sudo fanshim
Traceback (most recent call last):
  File "/usr/bin/fanshim", line 70, in <module>
    t = get_cpu_temp()
  File "/usr/bin/fanshim", line 38, in get_cpu_temp
    return psutil.sensors_temperatures()['cpu-thermal'][0].current
KeyError: 'cpu-thermal'
```

**Comment by fryfrog** [comment]
Well, this is weird... on my Arch Pi... its just called `cpu_thermal` instead of `cpu-thermal`. :/

```
0 ✓ fryfrog@arch-aarch64 ~ $ python
Python 3.7.3 (default, Jun 24 2019, 12:44:14)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.sensors_temperatures()['cpu-thermal'][0].current
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'cpu-thermal'
>>> psutil.sensors_temperatures()
{'cpu_thermal': [shwtemp(label='', current=45.622, high=80.0, critical=80.0)]}
>>> psutil.sensors_temperatures()['cpu_thermal'][0].current
46.16
```
